### PR TITLE
Add note about checking `.ruby-gemset`

### PR DESCRIPTION
**Pull request by marcrohloff**
Useful to know if you need compatibility with rvm based configurations

### CODE REVIEW

**Comment by jf** [comment]
thanks. I think "compatibility" can be confusing in this case. How do we improve this? Sure, `rbenv-gemset` will use `.ruby-gemset` as a fallback, but that in no way means that you can simply take a setup that uses rvm already and have `rbenv-gemset` work as is. You would still need to install gems to where `rbenv-gemset` expects them to be.

**Comment by marcrohloff** [comment]
Fair enough, I just felt that it needed a mention. It was important to my decision.

How about
```
If the .ruby-gemsets file does not exist rbenv will fallback to . ruby-gemsets . 
```
And maybe add something like
```
the same file used by rvm
```

**Comment by jf** [comment]
> Fair enough, I just felt that it needed a mention. It was important to my decision.
> 

Thanks for the note. I'd like to hear more about this - what is your situation and why was this important for you?


> How about
> 
> ```
> If the .ruby-gemsets file does not exist rbenv will fallback to . ruby-gemsets . 
> ```
> 
> And maybe add something like
> 
> ```
> the same file used by rvm
> ```

I think some version of this could work, as long as we do not give the impression that `rbenv-gemset` will reuse the same gemsets that rvm has created.

**Comment by marcrohloff** [comment]
OK, I updated the PR. I decided to just keep it simple.

Mostly that we have a team that is large enough that I cannot easily move everyone over. Nor do I wish to dictate what they use

**Comment by jf** [comment]
this is great, thanks! Just one fix, though: it's
```
If `.rbenv-gemsets` is not found ...
```

and not
```
If the `.ruby-gemsets` is not found ...
```

If you can correct that, I will get this merged.

**Comment by jf** [comment]
thanks, @marcrohloff . You missed something, but that's ok. I will take it from here. Thanks for the note!

**Pull request merged**
